name = "BurpBounty"
url = ["https://github.com/wagiro/BurpBounty"]
source = "https://github.com/wagiro/BurpBounty"
category = "tool-addon"
type = "Utils"
platform = ["linux", "macos", "windows", "burpsuite"]
lang = "BlitzBasic"
tags = []
