name = "reflected-parameters"
url = ["https://github.com/PortSwigger/reflected-parameters"]
source = "https://github.com/PortSwigger/reflected-parameters"
category = "tool-addon"
type = "Recon"
platform = ["linux", "macos", "windows", "burpsuite"]
lang = "Java"
tags = ["param"]
