name = "turbo-intruder"
url = ["https://github.com/PortSwigger/turbo-intruder"]
source = "https://github.com/PortSwigger/turbo-intruder"
category = "tool-addon"
type = "Utils"
platform = ["linux", "macos", "windows", "burpsuite"]
lang = "Kotlin"
tags = []
